feat: added user creation api
Think-Storm/Backend pull request #21
Opened 2024-06-06 08:44 UTC by hcanon42

2024-06-10 09:14 UTC, Harian-Elyoth requested changes
JSDoc to add.
Some verification and try/catch block to add also.
Another test on createUser

File should be grouped by commits also by commit : 
If you modify a file in the first commit it is not expected to be changed in another commit. Because the PR gets harder to review commit by commit if we make comment on a commit that is changed on the second one. 
The Idea for this PR is to have for example a commit with the ts files without the tests. And another commit with the ts file including the tests. and another commit for the .yml files.

2024-06-10 09:14 UTC, Harian-Elyoth commented on src/modules/user/dtos/createUser.dto.ts
> +  @IsNotEmpty()
Maybe we should add more verifications such as : 
`@MinLength(3, { message: 'Username must be at least 3 characters long.' })`
 `@MaxLength(15, { message: 'Username cannot be longer than 15 characters.' })`
 `@Matches(/^[a-zA-Z0-9_]+$/, { message: 'Username can only contain letters, numbers, and underscores.' })`

2024-06-10 09:14 UTC, Harian-Elyoth commented on src/modules/user/dtos/createUser.dto.ts
> +  @IsNotEmpty()
Maybe we should add more verifications such as :

`@MinLength(8, { message: 'Password must be at least 8 characters long.' })`
`@MaxLength(20, { message: 'Password cannot be longer than 20 characters.' })`
`@Matches(/^(?=.*[A-Z])(?=.*\d)[A-Za-z\d@$!%*?&]{8,}$/, { message: 'Password must contain at least one uppercase letter and one number.' })`

2024-06-10 09:14 UTC, Harian-Elyoth commented on src/modules/user/dtos/createUserResponse.dto.ts
> +  bio: string;
As it is optional should it be : 
`bio?: string;`

2024-06-10 09:14 UTC, Harian-Elyoth commented on src/modules/user/dtos/createUserResponse.dto.ts
> +  avatar: string;
As it is optional should it be : 
`avatar?: string;`

2024-06-10 09:14 UTC, Harian-Elyoth commented on src/modules/user/dtos/user.mapper.ts
> +  UserToCreateUserResponseDTO(user: User): CreateUserResponseDto {
We should use camelCase for typescript convention  ?

2024-06-10 09:14 UTC, Harian-Elyoth commented on src/modules/user/dtos/user.mapper.ts
> +  UserToCreateUserResponseDTO(user: User): CreateUserResponseDto {
Maybe also adding some JSDoc comments for the future documentation ? like 
~~~
/**
 * Maps a User entity to a CreateUserResponseDto
 * @param user - The User entity to be mapped
 * @returns A CreateUserResponseDto with the mapped data
*/
~~~

2024-06-10 09:14 UTC, Harian-Elyoth commented on src/modules/user/user.controller.ts
> +  async postGoodBye(@Body() body: CreateUserDto, @Res() res: Response) {
Rename the function createUser
Maybe scope the code into a try/catch block that can catch an instance of BadRequestException ?

2024-06-10 09:14 UTC, Harian-Elyoth commented on src/modules/user/user.module.ts
>  @Module({
JSDoc
~~~
/**
 * Module for user-related components and services
 */
~~~

2024-06-10 09:14 UTC, Harian-Elyoth commented on src/modules/user/user.repository.ts
> +  async getUserByEmail(email: string) {
JSDoc
~~~
  /**
   * Finds a user by email
   * @param email - The email of the user to find
   * @returns A promise resolving to a User object or null
   */
~~~

2024-06-10 09:14 UTC, Harian-Elyoth commented on src/modules/user/user.repository.ts
> +    return this.prisma.user.findFirst({
Scope it into a try catch block ?
~~~
try {
      return await this.prisma.user.findFirst({
        where: {
          email: {
            equals: email.toLowerCase(),
          },
        },
      });
    } catch (error) {
      // Handle error appropriately (e.g., log it)
      throw new Error('Error fetching user by email');
    }
~~~

2024-06-10 09:14 UTC, Harian-Elyoth commented on src/modules/user/user.repository.ts
> +  async createUser(
JSDoc
~~~
  /**
   * Creates a new user
   * @param createUserDto - The data transfer object containing user creation details
   * @param passwordSalt - The password salt for hashing
   * @returns A promise resolving to the created User object
   */
~~~

2024-06-10 09:14 UTC, Harian-Elyoth commented on src/modules/user/user.repository.ts
> +    return this.prisma.user.create({
Also scope it into a try catch block
~~~
    try {
      return await this.prisma.user.create({
        data: {
          username: createUserDto.username,
          email: createUserDto.email.toLowerCase(),
          password: createUserDto.password,
          passwordSalt: passwordSalt,
          fullName: createUserDto.fullName,
          bio: createUserDto.bio,
          birthdate: createUserDto.birthdate,
        },
      });
    } catch (error) {
      // Handle error appropriately (e.g., log it)
      throw new Error('Error creating user');
    }
~~~

2024-06-10 09:14 UTC, Harian-Elyoth commented on src/modules/user/user.service.ts
> +  async doesUserWithEmailExist(email: string): Promise<User> {
JSDoc
~~~
  /**
   * Checks if a user with the given email exists
   * @param email - The email to check
   * @returns A promise resolving to a User object or null
   */
~~~

2024-06-10 09:14 UTC, Harian-Elyoth commented on src/modules/user/user.service.ts
> +  async IsUserCreateDtoValid(dto: CreateUserDto) {
JSDoc
~~~
  /**
   * Validates the CreateUserDto
   * @param dto - The data transfer object to validate
   * @throws BadRequestException if the email is already in use
   */
~~~

2024-06-10 09:14 UTC, Harian-Elyoth commented on src/modules/user/user.service.ts
> +  async createUser(
JSDoc
~~~
 /**
   * Creates a new user
   * @param createUserDto - The data transfer object for creating a user
   * @returns A promise resolving to a CreateUserResponseDto
   */
~~~

2024-06-10 09:14 UTC, Harian-Elyoth commented on src/modules/user/user.service.ts
> +    const passwordInformation =
Scope it into try catch block
~~~
    try {
      const passwordInformation = await this.passwordEncryption.createSaltAndHashedPassword(createUserDto.password);
      createUserDto.password = passwordInformation.hashedPassword;
      const createdUser = await this.userRepository.createUser(createUserDto, passwordInformation.passwordSalt);
      return this.userMapper.userToCreateUserResponseDto(createdUser);
    } catch (error) {
      // Handle error appropriately (e.g., log it)
      throw new Error('Error creating user');
    }
~~~

2024-06-12 04:24 UTC, hcanon42 commented on src/modules/user/dtos/createUser.dto.ts
> +  @IsNotEmpty()
Shouldn't this be handle in the front-end though? Or should we do it in both back-end and front-end?

2024-06-12 04:24 UTC, hcanon42 commented on src/modules/user/dtos/createUser.dto.ts
> +  @IsNotEmpty()
Same comment as the one before

2024-06-12 04:28 UTC, hcanon42 commented on src/modules/user/dtos/createUserResponse.dto.ts
> +  bio: string;
I can but does it change anything?  Since it is the response DTO, the front-end will have to check it anyway, so whether the value isn't here or is null/undefined doesn't change anything does it ?

2024-06-12 04:28 UTC, hcanon42 commented on src/modules/user/dtos/createUserResponse.dto.ts
> +  avatar: string;
Same comment as the one before

2024-06-12 04:28 UTC, hcanon42 commented on src/modules/user/dtos/user.mapper.ts
> +  UserToCreateUserResponseDTO(user: User): CreateUserResponseDto {
yes my bad !

2024-06-12 04:35 UTC, hcanon42 commented on src/modules/user/user.controller.ts
> +  async postGoodBye(@Body() body: CreateUserDto, @Res() res: Response) {
Yeah the name has been changed in the wrong commit, I'll modify this

Actually, for the try catch, the exception is caught by a nestJS class that automatically sends back an HTTP response with the right status and message (that I initialized in the main.ts):
 ```app.useGlobalPipes(new ValidationPipe({ stopAtFirstError: true }));```

But if you prefer the try catch it's fine to me too, I just think that the controller will be more complex without a very good reason to it

2024-06-12 04:41 UTC, hcanon42 commented on src/modules/user/user.repository.ts
> +    return this.prisma.user.findFirst({
I think the repository should not hold any logic, and just do queries. For example this method could be also used to fetch the user in a getUserByEmail API, and in this case we would not want it to throw if it doesn't find anything. I really think the business logic should be held in the service :)

2024-06-12 04:42 UTC, hcanon42 commented on src/modules/user/user.repository.ts
> +    return this.prisma.user.create({
This I agree with, I will change it

2024-06-12 04:53 UTC, hcanon42 commented on src/modules/user/user.service.ts
> +    const passwordInformation =
Mmmmh the problem with this is that if we do a big try catch like this, it will be redundant with the errors thrown from the other functions because we'll have to catch every type of error, and I don't really see the point if it is already done by NestJs

2024-06-12 18:09 UTC, Harian-Elyoth requested changes
The last thing I forgot to mention before, just the readme in another commit and we are good to go :) !

2024-06-12 18:09 UTC, Harian-Elyoth commented on README.md
Should be in another commit

2024-06-17 11:47 UTC, Harian-Elyoth approved these changes

2024-06-17 11:47 UTC, merged