Feature/5 get project api
Think-Storm/Backend pull request #23
Opened 2024-06-10 09:15 UTC by hcanon42

2024-06-21 08:54 UTC, Harian-Elyoth commented
Need to change the commit name
feat: added GetProject api
chore: added tests to getProjectById API

2024-06-21 11:29 UTC, Harian-Elyoth requested changes
The commit name needs to be reword.
Otherwise it's almost good, I just notice some improvements that can be made

2024-06-21 11:29 UTC, Harian-Elyoth commented on src/modules/project/dtos/project.mapper.ts
> +   * @param user - The Project entity to be mapped
Change the name of this param

2024-06-21 11:29 UTC, Harian-Elyoth commented on src/modules/project/project.controller.ts
> +@Controller()
Maybe we should add a route prefix for the controller to avoid future conflicts and confusions

`@Controller('projects')`

2024-06-21 11:29 UTC, Harian-Elyoth commented on src/modules/project/project.controller.ts
> +  async getProjectById(@Param() param: GetProjectRequestDto) {
How about adding the nestjs/common validation pipe to validate the GetProjectRequestDto

`@UsePipes(new ValidationPipe({tranform: true}))`

2024-06-21 11:29 UTC, Harian-Elyoth commented on src/modules/project/project.module.ts
> + * Module for project-related components and services
Maybe a more precise description : 

```
/**
 * The ProjectModule is responsible for managing the project-related components
 * and services including controllers, services, repositories, and mappers.
 */
```

2024-06-21 11:29 UTC, Harian-Elyoth commented on src/modules/project/project.repository.ts
> +    return this.prisma.project.findUnique({
Maybe add a id number verification such as 

```
    if (!Number.isInteger(id) || id <= 0) {
      throw new NotFoundException(`Invalid project ID: ${id}`);
    }
```

2024-06-21 11:29 UTC, Harian-Elyoth commented on src/modules/project/project.repository.ts
> +    return this.prisma.project.findUnique({
Assure that the return project is not null also

```
    const project = await this.prisma.project.findUnique({
      where: {
        id: id,
      },
      include: { language: true, users: true },
    });

    if (!project) {
      throw new NotFoundException(`Project with ID ${id} not found`);
    }
```

2024-06-21 11:29 UTC, Harian-Elyoth commented on src/modules/project/project.repository.ts
> +  async getProjectById(id: number): Promise<Project> {
In the repository we should keep the DON (Data oriented naming) that is describe by the methods
find / update / create / delete
These methods use Prisma's generated methods (findUnique, create, update, delete) to perform CRUD operations.

2024-06-21 11:29 UTC, Harian-Elyoth commented on src/modules/project/project.controller.ts
> +  async getProjectById(@Param() param: GetProjectRequestDto) {
Maybe add a return type ?

 Promise<GetProjectResponseDto>

2024-06-21 21:42 UTC, Harian-Elyoth requested changes

2024-06-21 21:42 UTC, Harian-Elyoth commented on test/e2e/project.e2e-spec.ts
> +        .get(`/${createdProject.id}`)
having a more relevant path maybe.

.get(`/projects/${createdProject.id}`)

2024-06-21 21:42 UTC, Harian-Elyoth commented on test/e2e/project.e2e-spec.ts
> +    it('should return a 404 if user does not exist', async () => {
Maybe also add a 400 error code return if an Id is invalid

```
it('should return a 400 if id format is invalid', async () => {
      const invalidId = 'invalid-id';
      return request(app.getHttpServer()).get(`/projects/${invalidId}`).expect(400);
    });
```

2024-06-21 21:42 UTC, Harian-Elyoth commented on test/unit/modules/project/project.controller.spec.ts
> +  describe('getprojectFunction function', () => {
getProjectById function may be a better description and avoid confusion

2024-06-21 21:42 UTC, Harian-Elyoth commented on test/unit/modules/project/project.controller.spec.ts
> +    });
May also consider a test for the Project not found 

sth like this : 

```
it('should throw NotFoundException if project not found', async () => {
      // Mock service function to return null
      const serviceSpy = jest
        .spyOn(projectService, 'getProjectById')
        .mockResolvedValue(null);

      await expect(
        projectController.getProjectById({
          id: projectTestUtils.defaultGetProjectResponseDto.id,
        }),
      ).rejects.toThrow(NotFoundException);

      expect(serviceSpy).toHaveBeenCalledTimes(1);
      expect(serviceSpy).toHaveBeenCalledWith(
        projectTestUtils.defaultGetProjectResponseDto.id,
      );
    });
```

2024-06-21 21:42 UTC, Harian-Elyoth commented on test/unit/modules/project/project.repository.spec.ts
> +  beforeAll(async () => {
Maybe beforeEach should be better for test isolation ?

2024-06-21 21:42 UTC, Harian-Elyoth commented on test/unit/modules/project/project.repository.spec.ts
> +  beforeAll(async () => {
Or keeping before all for the project inputs as a main setup

2024-06-21 21:42 UTC, Harian-Elyoth commented on test/unit/modules/project/project.repository.spec.ts
> +  afterEach(async () => {
We should try to not deleteMany after each test case but keeping relevant information to not slow down the tests process ?

2024-06-21 21:42 UTC, Harian-Elyoth commented on test/unit/modules/project/project.repository.spec.ts
> +      const getProjectByIdResponse = await projectRepository.getProjectById(
Explicitly typed the return values of getProjectById as Project | null to ensure type safety and clarity in the tests.

```
        // Retrieve the created Project by ID
        const getProjectByIdResponse: Project | null = await projectRepository.getProjectById(
          insertedProject.id,
        );
```

2024-06-21 21:42 UTC, Harian-Elyoth commented on test/unit/modules/project/project.repository.spec.ts
> +      const getProjectByIdResponse = await projectRepository.getProjectById(
type safety : 
```
        const getProjectByIdResponse: Project | null = await projectRepository.getProjectById(
          insertedProject.id + 1,
        );
```

2024-06-21 21:42 UTC, Harian-Elyoth commented on test/unit/modules/project/project.utils.ts
> +  async createProjectInDB(
JSDOC

```
  /**
   * Creates a project in the database.
   * @param prismaService - The Prisma service for database access.
   * @param userRepository - The user repository for user-related database operations.
   * @returns The created project.
   */
```

2024-06-21 21:42 UTC, Harian-Elyoth commented on test/unit/modules/project/project.utils.ts
> +    prismaService: PrismaService,
Here, prismaService and userRepository are passed as parameters to the createProjectInDB method. This makes it necessary to pass these dependencies every time you call the method, which can be cumbersome and error-prone.

Use constructor injection to inject PrismaService and UserRepository when creating an instance of ProjectTestUtils. This way, these dependencies are available to all methods within the class without having to pass them around.

```
  constructor(
    private readonly prismaService: PrismaService,
    private readonly userRepository: UserRepository,
  ) {}
```

Use them as this.prismaService / this.prismaRepository etc

2024-06-27 07:46 UTC, hcanon42 commented on src/modules/project/dtos/project.mapper.ts
> +   * @param user - The Project entity to be mapped
actually this part is already handled by the router in the app.module file, and putting it here too would change the path of the apis to '/projects/projects/'

2024-06-27 07:47 UTC, hcanon42 commented on src/modules/project/project.controller.ts
> +  async getProjectById(@Param() param: GetProjectRequestDto) {
This is already by the class validator in the dto file

2024-06-27 07:48 UTC, hcanon42 commented on src/modules/project/project.repository.ts
> +    return this.prisma.project.findUnique({
it is already checked by the class validator dto

2024-06-27 07:50 UTC, hcanon42 commented on src/modules/project/project.repository.ts
> +    return this.prisma.project.findUnique({
the logic should not be handled in the repository, that's why I did this check in the service

2024-06-27 07:54 UTC, hcanon42 commented on test/e2e/project.e2e-spec.ts
> +        .get(`/${createdProject.id}`)
since my fixture for the tests only loads the project module, the default path is 'projects/' so when I do:
```/${createdProject.id}```
it is actually:
```/projects/${createdProject.id}```

2024-06-27 07:55 UTC, hcanon42 commented on test/unit/modules/project/project.controller.spec.ts
> +  describe('getprojectFunction function', () => {
lol yeah missclick I think

2024-06-27 07:59 UTC, hcanon42 commented on test/unit/modules/project/project.controller.spec.ts
> +    });
Since the exception is thrown in the service there is no case where the controller receives a null project, either the project is found and the controller gets it or the project is not and the exception is thrown, thus not calling back the controller

2024-06-27 08:01 UTC, hcanon42 commented on test/unit/modules/project/project.repository.spec.ts
> +  beforeAll(async () => {
I have an aftereach that does clean the db everytime, and initiating the module for each test would take a lot of time for nothing I think

2024-06-27 08:03 UTC, hcanon42 commented on test/unit/modules/project/project.repository.spec.ts
> +  afterEach(async () => {
It would be very hard to understand while reading the tests, make it more unsure due to more possible mistakes while creating the tests and as you said in your comment earlier, test isolation is a very important part of repository testing

2024-06-27 08:09 UTC, hcanon42 commented on test/unit/modules/project/project.repository.spec.ts
> +      const getProjectByIdResponse = await projectRepository.getProjectById(
We can put it for the clarification, but the type is already ensured by the typing of the return value of projectRepository.getProjectById method.

2024-06-27 08:11 UTC, hcanon42 commented on test/unit/modules/project/project.repository.spec.ts
> +      const getProjectByIdResponse = await projectRepository.getProjectById(
same

2024-06-27 08:34 UTC, hcanon42 commented on test/unit/modules/project/project.utils.ts
> +    prismaService: PrismaService,
The problem with this is that when I use the projectTestUtils class for something else than this specific method, I have to initialize the prismaService and UserRepository, which I don't have to do for now. I can do it but it would add a lot useless code, which might confuse the people trying to understand why these services/repository are initialized

2024-06-27 08:34 UTC, hcanon42 commented on src/modules/project/dtos/project.mapper.ts
> +   * @param user - The Project entity to be mapped
yes

2024-06-27 08:40 UTC, hcanon42 commented on src/modules/project/project.controller.ts
> +@Controller()
This is already done by the router in the app.module, because adding it here would change the path of the apis a second time

2024-06-27 08:41 UTC, hcanon42 commented on test/unit/modules/project/project.utils.ts
> +  async createProjectInDB(
yes

2024-06-27 08:42 UTC, hcanon42 commented on test/e2e/project.e2e-spec.ts
> +    it('should return a 404 if user does not exist', async () => {
yes

2024-06-27 08:42 UTC, hcanon42 commented on src/modules/project/project.controller.ts
> +  async getProjectById(@Param() param: GetProjectRequestDto) {
why not

2024-06-27 08:43 UTC, hcanon42 commented on src/modules/project/project.repository.ts
> +  async getProjectById(id: number): Promise<Project> {
ok

2024-06-27 08:44 UTC, hcanon42 commented on src/modules/project/project.module.ts
> + * Module for project-related components and services
ok

2024-07-01 10:24 UTC, Harian-Elyoth approved these changes

2024-07-01 11:07 UTC, merged