Feature/22 make get user by id api
Think-Storm/Backend pull request #35
Opened 2024-06-30 09:19 UTC by kimdahee0815

2024-07-01 07:06 UTC, hcanon42 requested changes
Overall very good but I want the others opinion about the error management because I still don't think it will be beneficent for our project.

Also can you please reduce the number of commits to 2 or 3 max ? A commit should represent a feature, not a file. We should be able to roll back to any commit and have the project working (with less features, but still working).
You may want to do something like:

- feature: add GetUserById API
- chore: add tests to GetUserById API
- (chore : add customized exception filter)

2024-07-01 07:06 UTC, hcanon42 commented on package.json
> +    "start:dev": "SET NODE_ENV=development&&nest start --watch",
```suggestion
    "start:dev": "set NODE_ENV=development && nest start --watch",
```

2024-07-01 07:06 UTC, hcanon42 commented on package.json
> +    "start:prod": "SET NODE_ENV=production&&node dist/main",
```suggestion
    "start:prod": "set NODE_ENV=production && node dist/main",
```

2024-07-01 07:06 UTC, hcanon42 commented on src/common/exception-filter/serviceExceptionFilter.ts
> +}
I still disagree with this. But we've talk about it too much already, let's make a choice.
@Harian-Elyoth @bruadarach What do you think about this ? It's removing the native error handling from NestJS to implement our customized one. It allows us to change the format of the error responses (for example add a new field with the stack trace when we're working with the dev). But it is useless for now and it means that every time we get a new error we have to add it here. It also complexifies the codebase where it is not necessary. Error conventions are here for something in my opinion, and if we don't want to use premade features I don't understand why we chose a high level framework.

2024-07-01 07:06 UTC, hcanon42 commented on src/common/exception-filter/serviceExceptionFilter.ts
> +}
If other people agree with this change let's do it

2024-07-01 07:06 UTC, hcanon42 commented on src/common/enums/errorMessages.ts
> +  VALIDATION_ERROR = 'Validation is failed.',
Can you make the errors more specific please ? like why is the user invalid, why is the validation failed, what validation is failed.... You can even put variables as I did in my [pull-request](https://github.com/Think-Storm/Backend/pull/23)

2024-07-01 07:06 UTC, hcanon42 commented on src/modules/user/user.controller.ts
> +  async getUserById(@Param('id') userId: number): Promise<UserResponseDto> {
how do you know which validation processed failed with this method ? You may get a 400 error but we need to tell the frontend what it did wrong otherwise it cannot correct it

2024-07-01 10:16 UTC, Harian-Elyoth commented
The git manual recommand this for the commits : 
Commits are separated by file type / features / addition / deletion
Let's say your branch is one feature : it could be one commit
Then you have to separate : 
- 1 commit for the .eslint.js file
- 1 commit for the package.json file
- 1 commit for the addition of your expection-service .ts files (because it's an addition) (if we keep it)
- 1 commit for your .ts files

2024-07-01 10:30 UTC, kimdahee0815 commented on src/common/exception-filter/serviceExceptionFilter.ts
> +}
We are using the premade features (class-validator), but we simply just wrap this error with customized format. Even the errors that came from class-validator will be covered and all the other errors that are not predictable will be covered here. Also, when you use customized error format, you can find out where this error came from by just looking at the stack trace. Applying customized error will prevent the code from having multiple unexpected errors (not handled) and i don't believe that we have to add new error handling features in this class everytime we've got new errors. Most of the errors are bad request exception(400) (including validation error), unauthorized exception(401), not found(404), server error(500).

2024-07-01 10:30 UTC, kimdahee0815 commented on package.json
> +    "start:dev": "SET NODE_ENV=development&&nest start --watch",
I've tried this! It didn't work with the space :(

2024-07-01 10:50 UTC, kimdahee0815 commented on src/common/enums/errorMessages.ts
> +  VALIDATION_ERROR = 'Validation is failed.',
These messages are not specific, because these errors will happen when we do other features as well.
For example, when we develop project or account api, these error messages can be used again!
So i didn't create specific error message here.

2024-07-01 10:52 UTC, kimdahee0815 commented on src/modules/user/user.controller.ts
> +  async getUserById(@Param('id') userId: number): Promise<UserResponseDto> {
This validation error will be specified in error message format!

2024-07-04 20:09 UTC, Harian-Elyoth requested changes
Reduce the number of commit and it's good for me 
You have 17 commits try to squash them :)

2024-07-05 14:53 UTC, Harian-Elyoth approved these changes, later dismissed

2024-07-10 09:16 UTC, hcanon42 approved these changes, later dismissed
A few small things

2024-07-10 09:16 UTC, hcanon42 commented on src/modules/user/user.repository.ts
> +// import { errorMessages } from 'src/common/enums/errorMessages';
Can you remove commented lines please ?

2024-07-10 09:16 UTC, hcanon42 commented on src/common/enums/errorMessages.ts
> +  VALIDATION_ERROR: 'Validation is failed.',
```suggestion
  VALIDATION_ERROR: 'The validation has failed.',
```

or:

```suggestion
  VALIDATION_ERROR: 'Validation failed.',
```

2024-07-10 09:16 UTC, hcanon42 commented on src/common/enums/errorMessages.ts
> +  ENTITY_NOT_FOUND: (id: string) => `Entity with id ${id} was not found.`,
I think it is better if we have a message like this for every entity, because the frontend doesn't know what the backend is doing, so it doesn't know what entity you are talking about.

2024-07-10 09:16 UTC, hcanon42 commented on src/common/exception-filter/serviceExceptionFilter.ts
> +          message: 'Something went very wrong! This is not Operational Error.',
constant ?

2024-07-10 09:16 UTC, hcanon42 commented on src/common/exception-filter/serviceExceptionFilter.ts
> +          message: 'Something went very wrong! This is not Operational Error.',
constant ?

2024-07-10 09:16 UTC, hcanon42 commented on src/modules/user/user.controller.ts
> +// import { getUserDto } from './dtos/getUser.dto';
to remove

2024-07-10 09:35 UTC, kimdahee0815 commented on src/common/enums/errorMessages.ts
> +  ENTITY_NOT_FOUND: (id: string) => `Entity with id ${id} was not found.`,
Wouldn't it be clear because you have every resources in REST api?
ex. project/:id , user/:id ?

2024-07-10 09:41 UTC, kimdahee0815 commented on src/common/enums/errorMessages.ts
> +  VALIDATION_ERROR: 'Validation is failed.',
done

2024-07-10 09:41 UTC, kimdahee0815 commented on src/common/exception-filter/serviceExceptionFilter.ts
> +          message: 'Something went very wrong! This is not Operational Error.',
i've included error object in this response, would it be right solution?

2024-07-10 09:42 UTC, kimdahee0815 commented on src/common/exception-filter/serviceExceptionFilter.ts
> +          message: 'Something went very wrong! This is not Operational Error.',
i've included error object in this response, would it be right solution?

2024-07-10 09:42 UTC, kimdahee0815 commented on src/modules/user/user.repository.ts
> +// import { errorMessages } from 'src/common/enums/errorMessages';
done

2024-07-10 09:43 UTC, kimdahee0815 commented on src/modules/user/user.controller.ts
> +// import { getUserDto } from './dtos/getUser.dto';
done

2024-07-11 04:36 UTC, hcanon42 commented on src/common/enums/errorMessages.ts
> +  ENTITY_NOT_FOUND: (id: string) => `Entity with id ${id} was not found.`,
Well it is a possibility that for example the create User API also creates a userProfile entity in which case more information would be nice

2024-07-11 04:38 UTC, hcanon42 commented on src/common/exception-filter/serviceExceptionFilter.ts
> +          message: 'Something went very wrong! This is not Operational Error.',
I'm sorry I don't understand what you're saying 😢 I just mean that there should not be any "magic" strings in the code except in specific files

2024-07-11 10:15 UTC, kimdahee0815 commented on src/common/enums/errorMessages.ts
> +  ENTITY_NOT_FOUND: (id: string) => `Entity with id ${id} was not found.`,
i've only made get API for common, not create user api :)

2024-07-11 10:16 UTC, kimdahee0815 commented on src/common/enums/errorMessages.ts
> +  ENTITY_NOT_FOUND: (id: string) => `Entity with id ${id} was not found.`,
well if you create user, then rest api method would be 'POST', right? 
then you will be able to tell the that user entity wasn't found. :)

2024-07-11 10:19 UTC, kimdahee0815 commented on src/common/exception-filter/serviceExceptionFilter.ts
> +          message: 'Something went very wrong! This is not Operational Error.',
oh this message is for when the undefined error occurs, which are not operational error. 
So, when you see this error, you know that the error was not expected by developers, so you could anaylze the error by the error object i put inside the response.json.
Did you get what i mean?

2024-07-11 10:29 UTC, hcanon42 commented on src/common/enums/errorMessages.ts
> +  ENTITY_NOT_FOUND: (id: string) => `Entity with id ${id} was not found.`,
When I create a project I also have to check if the founder does exist, which might throw an exception when I do not found the user for example...

2024-07-11 10:32 UTC, hcanon42 commented on src/common/exception-filter/serviceExceptionFilter.ts
> +          message: 'Something went very wrong! This is not Operational Error.',
Yeah sorry I should have been clearer ^^ moving the error message to the errorMessage file was what I was referring to ahah

2024-07-11 10:34 UTC, hcanon42 commented on src/common/enums/errorMessages.ts
> +  ENTITY_NOT_FOUND: (id: string) => `Entity with id ${id} was not found.`,
It's not very long to implement and quite useful :)

2024-07-11 11:44 UTC, kimdahee0815 commented on src/common/enums/errorMessages.ts
> +  ENTITY_NOT_FOUND: (id: string) => `Entity with id ${id} was not found.`,
i've fixed it! 
entity not found message is still same, but i added parameter so that you could pass what subject you are looking for

2024-07-11 11:44 UTC, hcanon42 approved these changes

2024-07-11 11:52 UTC, merged