Feature/3 log in api
Think-Storm/Backend pull request #42
Opened 2024-07-17 06:34 UTC by kimdahee0815

2024-08-05 07:05 UTC, hcanon42 requested changes
Overall very good, the JWT is understood, just a few clean code practices are missing

2024-08-05 07:05 UTC, hcanon42 commented on src/common/passwordEncryption.ts
> +  }
usually we try to use a verb when naming a function, so this is a bit weird because it looks like you are correcting the password. Maybe you could do this: 

```suggestion
  async isPasswordCorrect(candidatePassword: string, userPassword: string) {
    return await bcrypt.compare(candidatePassword, userPassword);
  }
```

2024-08-05 07:05 UTC, hcanon42 commented on src/modules/auth/auth.service.ts
> +      !(await this.passwordEncryption.correctPassword(password, user.password))
Don't you have to use the PasswordSalt ?

2024-08-05 07:05 UTC, hcanon42 commented on src/common/exception-filter/serviceException.ts
> +  };
AuthException might be a bit vague, because it could be 401 or 403, maybe you can just rename it to unauthorizedException ? 

```suggestion
  static UnauthorizedException = (message: string): ServiceException => {
    return new ServiceException(message, 401);
  };
```

2024-08-05 07:05 UTC, hcanon42 commented on src/modules/auth/auth.module.ts
> +  providers: [
In the providers, you should only add what is relevant to the current module, and import the rest, so for example     UserRepository and PrismaService should not be in the providers imo

2024-08-05 07:05 UTC, hcanon42 commented on src/modules/auth/auth.repository.ts
> +}
why do you need an empty repository ?

2024-08-05 07:05 UTC, hcanon42 commented on src/modules/auth/auth.service.ts
> +  }
To keep some kind of uniformity, we should do either only do anonymous functions like "signToken = (id: number) => {" or only regular methods like : ""getToken(user: UserResponseDto): string {

2024-08-05 07:05 UTC, hcanon42 commented on src/modules/auth/auth.service.ts
> +          Number(process.env.JWT_COOKIE_EXPIRES_IN) * 24 * 60 * 60 * 1000,
Please use constants instead of magic numbers

```suggestion
          Number(process.env.JWT_COOKIE_EXPIRES_IN) * DAY_TO_MILISECONDS_RATIO,
```

2024-08-05 07:05 UTC, hcanon42 commented on src/modules/auth/jwt/jwt.strategy.ts
> +    }
instead of 4 steps and comments, please split into functions

2024-08-05 07:05 UTC, hcanon42 commented on src/modules/auth/local/local.strategy.ts
> +    );
If you have to comment the steps of a function, usually that's a sign for you to split into two functions

2024-08-05 07:05 UTC, hcanon42 commented on src/modules/user/user.controller.ts
> +//import { JwtAuthGuard } from '../auth/jwt/jwt.guard';
no comments

2024-08-05 07:05 UTC, hcanon42 commented on src/modules/user/user.controller.ts
> +  //UseGuards,
no comments

2024-08-05 07:05 UTC, hcanon42 commented on src/modules/user/user.controller.ts
> +  //@UseGuards(JwtAuthGuard)
please remove commented lines

2024-08-05 07:05 UTC, hcanon42 commented on src/modules/user/user.module.ts
> +    AuthRepository,
to import

2024-08-05 07:05 UTC, hcanon42 commented on src/prisma/prisma.module.ts
> +    };
What is this for ?

2024-08-05 07:05 UTC, hcanon42 commented on src/common/enums/errorMessages.ts
> +  BAD_REQUEST_LOGIN_ERROR: 'Please provide email or password.',
Seems more logical this way, given you code:
```suggestion
  BAD_REQUEST_LOGIN_ERROR: 'Please provide email and password.',
```

2024-08-05 08:22 UTC, kimdahee0815 commented on src/modules/auth/auth.service.ts
> +      !(await this.passwordEncryption.correctPassword(password, user.password))
https://stackoverflow.com/questions/13023361/how-does-node-bcrypt-js-compare-hashed-and-plaintext-passwords-without-the-salt

It is possible withtout the password salt when we use bcrypt.compare function!

2024-08-05 08:38 UTC, kimdahee0815 commented on src/modules/auth/auth.module.ts
> +  providers: [
if UserRepository is removed from providers, it spits an error. 
That is because AuthService has dependency injection for userRepository.
Also, if AuthRepository has DI for PrismaService.

2024-08-05 08:40 UTC, kimdahee0815 commented on src/modules/auth/auth.repository.ts
> +}
Just in case, i made this repository because this can be necessary in the future. 
we might need to directly get data from database for Auth module as well, but if it is better to remove because this repository is not used here in this branch, i will remove it!

2024-08-05 08:51 UTC, kimdahee0815 commented on src/modules/user/user.controller.ts
> +//import { JwtAuthGuard } from '../auth/jwt/jwt.guard';
This is for testing purpose. Could you remove the comment and test if this works well?
If it works okay, comment below, and i will remove this line!

2024-08-05 08:52 UTC, kimdahee0815 commented on src/modules/user/user.controller.ts
> +  //UseGuards,
This is for testing purpose. Could you remove the comment and test if this works well?
If it works okay, comment below, and i will remove this line!

2024-08-05 08:52 UTC, kimdahee0815 commented on src/modules/user/user.controller.ts
> +  //@UseGuards(JwtAuthGuard)
This is for testing purpose. Could you remove the comment and test if this works well?
If it works okay, comment below, and i will remove this line!

2024-08-05 08:54 UTC, kimdahee0815 commented on src/modules/user/user.module.ts
> +    AuthRepository,
do you mean that i should remove these two lines?
It gives the errors, same reason above.

2024-08-05 08:55 UTC, kimdahee0815 commented on src/prisma/prisma.module.ts
> +    };
This code is for prismaService singleton. 
In the test code, it keeps creating prsimaservice instance so it gives warning.
This code prevents prisma service instance from being created constantly and only creates one instance while we do the testing.

2024-08-05 08:57 UTC, kimdahee0815 commented on src/common/enums/errorMessages.ts
> +  BAD_REQUEST_LOGIN_ERROR: 'Please provide email or password.',
done

2024-08-05 08:58 UTC, kimdahee0815 commented on src/common/passwordEncryption.ts
> +  }
done

2024-08-05 08:58 UTC, kimdahee0815 commented on src/common/exception-filter/serviceException.ts
> +  };
done!
I also created forbiddenException for 403 error.

2024-08-05 08:59 UTC, kimdahee0815 commented on src/modules/auth/auth.service.ts
> +  }
done
changed to annonymous function.

2024-08-05 09:00 UTC, kimdahee0815 commented on src/modules/auth/auth.service.ts
> +          Number(process.env.JWT_COOKIE_EXPIRES_IN) * 24 * 60 * 60 * 1000,
done

2024-08-05 10:09 UTC, kimdahee0815 commented on src/modules/auth/jwt/jwt.strategy.ts
> +    }
done

2024-08-05 10:13 UTC, kimdahee0815 commented on src/modules/auth/local/local.strategy.ts
> +    );
done

2024-09-09 07:34 UTC, hcanon42 commented on src/modules/auth/auth.repository.ts
> +}
We can add it back when we need it then :)

2024-09-11 06:07 UTC, hcanon42 commented on src/modules/user/user.controller.ts
> +  //@UseGuards(JwtAuthGuard)
We should not really put code that is used solely for tests insides our modules, is there no solution that only puts code inside the tests files ?

2024-09-11 06:43 UTC, hcanon42 commented on src/modules/auth/auth.module.ts
> +  providers: [
I think there is a small misconception of the difference between imports and providers:
- Providers are files (not modules) that are part of the current module and constitute the module. Here should be AuthService, JWTStrategy.... 
- Imports are modules (not specific files) from which you want some specific providers. Here for example you should import UserModule, use UserRepository in your providers, and export UserRepository in the User module

2024-09-11 06:46 UTC, hcanon42 commented on src/modules/auth/auth.module.ts
> +  providers: [
So in short, if a file has a logic that is linked to the user (such as UserRepository) it will be a provider of the UserModule, and if you want to use UserRepository in another module, please import UserModule

2024-09-11 06:47 UTC, hcanon42 commented on src/modules/user/user.module.ts
> +    AuthRepository,
I explained above why

2024-09-11 06:49 UTC, hcanon42 commented
Can you also do the same for the project controller please ? :)

2024-09-12 04:02 UTC, kimdahee0815 commented on src/modules/auth/auth.module.ts
> +  providers: [
I think there's no need to use UserRepository in providers when you import UserModule? 
So i left out that part
Also, if you use global decorater, you don't need to import PrismaModule
I changed AuthModule to global Module so that other modules can use without importing AuthModule. AuthModule will be used in different modules often, since it has authentication and authorization logic in there

2024-09-12 04:03 UTC, kimdahee0815 commented on src/modules/auth/auth.repository.ts
> +}
got it! for now it is removed :)

2024-09-12 04:05 UTC, kimdahee0815 commented on src/modules/user/user.controller.ts
> +  //@UseGuards(JwtAuthGuard)
this is for testing purpose before rebasing all the codes to develop branch (just letting know what should be done to test this)
I will remove this part after going through all the tests in other developer's local
Of course you can see that all the tests are passed running by npm run test:full, but it is necessary to check if it really works using API calls directly

2024-09-14 12:05 UTC, hcanon42 commented on src/modules/auth/auth.module.ts
> +  providers: [
yes I meant be a provider IN the UserModule file

2024-09-14 12:06 UTC, hcanon42 commented on src/modules/auth/auth.module.ts
> +  providers: [
It seems like a good idea for the global module of Authmodule!

2024-09-15 03:32 UTC, kimdahee0815 commented on src/modules/auth/auth.module.ts
> +  providers: [
yeah In the usermodule userRepository should be a provider, but in other modules you don't have to put userRepository as a provider after you import usermodule :)

2024-09-21 04:15 UTC, merged