Feature/58 register api
Think-Storm/Backend pull request #70
Opened 2024-10-24 14:03 UTC by kimdahee0815

2024-11-01 14:20 UTC, Harian-Elyoth commented
Some of the src development are in different commit than the first auth development commit. and if you are using special package, they should be included before your development. 
Should look sth like 
1. Include packages etc
2. all your development commits
3. all your tests commits
4. Others

@hcanon42 The docker solution was made because during the E2E Test development there was a problem related to the database, the datas were persistent. Can we try to fix this problem first (there is quite no reason that it works before and not now ^^). If we really can't, let's have some testing container artifacts and a better CI/CD pipeline.

2024-11-01 21:37 UTC, Harian-Elyoth requested changes
Modify your commit to have one commit for the packages / one commit for the development and one commit for your tests.

You can remove all docker relative content since it works in a standalone way

2024-11-04 05:32 UTC, kimdahee0815 commented
Arranged all commits, so would appreciate if you check again! :)

2024-11-07 04:27 UTC, hcanon42 requested changes
Just a quick question / change but overall good :D
The tests are nicely done !

2024-11-07 04:27 UTC, hcanon42 commented on src/modules/auth/auth.repository.ts
> +  }
why create another createUser fonction while we already have one in User.repository.ts ?

2024-11-07 04:27 UTC, hcanon42 commented on src/modules/auth/auth.service.ts
> +
These functions already exist in User, they should be exported in userModule and used as imports here

2024-11-07 04:27 UTC, hcanon42 commented on src/modules/auth/auth.service.ts
> +  };
Same for this one, please use the function present in the User service file

2024-11-07 04:27 UTC, hcanon42 commented on src/modules/user/user.repository.ts
> -    }
why are you deleting this from here ? The User creation should be in the user module and used in auth and not the other way around

2024-11-07 04:27 UTC, hcanon42 commented on src/modules/user/user.service.ts
> -
same question

2024-11-07 04:27 UTC, hcanon42 commented on src/prisma/prisma.dbreset.ts
> +      );
is there anyway to use this prisma commands instead of hardcoded SQL ?

2024-11-07 09:59 UTC, kimdahee0815 commented on src/modules/auth/auth.repository.ts
> +  }
createUser logic should be dealt within auth part, so I moved whole logic into auth
Because it needs the authorization when we register users

2024-11-07 10:02 UTC, kimdahee0815 commented on src/modules/auth/auth.service.ts
> +
Same answer as above

2024-11-07 10:02 UTC, kimdahee0815 commented on src/modules/auth/auth.service.ts
> +  };
Same answer as above

2024-11-07 10:02 UTC, kimdahee0815 commented on src/modules/user/user.repository.ts
> -    }
Same answer as above

2024-11-07 10:02 UTC, kimdahee0815 commented on src/modules/user/user.service.ts
> -
Same answer as above

2024-11-07 10:39 UTC, kimdahee0815 commented on src/prisma/prisma.dbreset.ts
> +      );
I've tried to find another solution, which is prisma migrate reset, but i think this can't be applied since reset needs to be done every time each tests finishes!
if you find any other solution, let me know and I'll try to apply that :)

2024-11-08 06:26 UTC, Harian-Elyoth commented on src/modules/auth/auth.repository.ts
> +  }
Hm I think that since we ask for the birthdate, bio, full name. It's still related to the user. It's not just about email and password here. I think personally that when you create an account, that can be related to the auth but here you create a user. So might be more logical to keep createUser in the User module. If we want to follow that logic, we dont use user, we split accounts and profiles but since you have one profile per account it's incoherent to have these database tabs

2024-11-08 08:32 UTC, hcanon42 approved these changes
:D

2024-11-08 09:09 UTC, Harian-Elyoth approved these changes

2024-11-08 09:09 UTC, merged