Feature/65 newsletter waiting list api
Think-Storm/Backend pull request #71
Opened 2024-11-02 08:54 UTC by hcanon42

2024-11-18 03:48 UTC, kimdahee0815 commented
Everything except for the reviews seems to be great! :)

2024-11-18 03:49 UTC, kimdahee0815 requested changes

2024-11-18 03:49 UTC, kimdahee0815 commented on test/unit/modules/user/user.controller.spec.ts
> -      const validatorSpy = jest.spyOn(userService, 'isUserCreateDtoValid');
isUserCreateDtoValid does not return promise value
So there shouldn't be mockResolvedValue added

2024-11-18 03:49 UTC, kimdahee0815 commented on test/e2e/waitingListUser.e2e-spec.ts
> +  });
deleteMany shouldn't be used to delete data from database because id doesn't get initialized by 1
Could you use refreshDatabase function that was created recently? 
add this part to afterAll and beforeEach and database will be refreshed everytime test finishes

2024-11-18 03:49 UTC, kimdahee0815 commented on src/modules/waiting_list_user/waitingListUser.service.ts
> +  async isWaitingListUserCreateDtoValid(dto: CreateWaitingListUserDto) {
should it be async function?
I think it doesn't need to return promise since it just checks if there user exists
if user doesn't exist, then it just throws error

2024-11-18 03:57 UTC, kimdahee0815 requested changes

2024-11-18 03:57 UTC, kimdahee0815 commented on src/modules/waiting_list_user/dtos/createWaitingListUser.dto.ts
could you add swagger docs here?

2024-11-18 03:57 UTC, kimdahee0815 commented on src/modules/waiting_list_user/dtos/waitingListUser.mapper.ts
same here for swagger docs!

2024-11-18 03:57 UTC, kimdahee0815 commented on src/modules/waiting_list_user/waitingListUser.controller.ts
same here for swagger docs!

2024-11-18 03:57 UTC, kimdahee0815 commented on src/modules/waiting_list_user/dtos/waitingListUserResponse.dto.ts
same here for swagger docs!

2024-11-19 04:20 UTC, hcanon42 commented on test/unit/modules/user/user.controller.spec.ts
> -      const validatorSpy = jest.spyOn(userService, 'isUserCreateDtoValid');
I changed this because if I didn't add the mockResolvedValue it would actually run the function instead of mocking it

2024-11-19 04:21 UTC, hcanon42 commented on test/e2e/waitingListUser.e2e-spec.ts
> +  });
Sure !

2024-11-19 04:31 UTC, hcanon42 commented on src/modules/waiting_list_user/waitingListUser.service.ts
> +  async isWaitingListUserCreateDtoValid(dto: CreateWaitingListUserDto) {
I think every database/prisma function, such as this.prisma.waitingListUser.findUnique, are async and return a Promise, so in order to handle it correctly, I have to put async on the function that calls it too

2024-11-19 04:31 UTC, hcanon42 commented on src/modules/waiting_list_user/dtos/createWaitingListUser.dto.ts
I will!

2024-11-19 06:41 UTC, hcanon42 commented on src/modules/waiting_list_user/dtos/createWaitingListUser.dto.ts
maybe we should wait for you to merge the swagger pull request then

2024-11-20 22:31 UTC, kimdahee0815 commented on test/unit/modules/user/user.controller.spec.ts
> -      const validatorSpy = jest.spyOn(userService, 'isUserCreateDtoValid');
When you use 'jest.spyOn' that is doing mocking itself.
If you call userService.isUserCreateDtoValid(), then the actual function is called instead of mocking.

2025-01-20 07:52 UTC, kimdahee0815 requested changes
Good job testing on mailservice! I learned new facts about mocking :D
There are some parts I commented on for review. 
If there is any question or any parts you don't agree, let me know, I'll check again!

2025-01-20 07:52 UTC, kimdahee0815 commented on test/e2e/waitingListUser.e2e-spec.ts
> +  });
refreshDataBase should also be added in afterAll to clear every data just to be sure!
Also, could you add refreshDataBase file to pass e2e test?

2025-01-20 07:52 UTC, kimdahee0815 commented on src/modules/waiting_list_user/dtos/createWaitingListUser.dto.ts
swagger docs were merged! :)

2025-01-20 07:52 UTC, kimdahee0815 commented on prisma/schema.prisma
>    projects          Project[]
prisma file needs to go to feat: add waiting_list_user table in db commit!

2025-01-20 07:52 UTC, kimdahee0815 commented on src/app.module.ts
>    ],
module file goes to feat: add create waiting list user api commit!

2025-01-20 07:52 UTC, kimdahee0815 commented on src/modules/newsletter/dtos/createNewsletterSubscription.dto.ts
> +}
All the files related to newsletter folder should go to waiting list user api commit :-)

2025-01-20 07:52 UTC, kimdahee0815 commented on test/e2e/newsletter.e2e-spec.ts
> +});
afterAll(async () => {
    await prismaService.$disconnect();
    await refreshDatabase();
  });
and in beforeEach await refreshDatabase(); should be added here to clean up the data that we tested before

2025-01-20 07:52 UTC, kimdahee0815 commented on test/unit/modules/newsletter/newsletter.repository.spec.ts
> +  });
I think instead of deleteMany function, you can try using refreshDatabase function here.
Adding deleteMany everytime we create new modules might not be that efficient!

2025-01-20 07:52 UTC, kimdahee0815 commented on test/unit/modules/newsletter/newsletter.repository.spec.ts
> +    });
Shouldn't there be 404 error when we retrieve non exist newsletterSubscription?

2025-01-20 07:52 UTC, kimdahee0815 commented on test/unit/modules/newsletter/newsletter.service.spec.ts
> +      expect(spy).toHaveBeenCalledTimes(1);
this should throw BadRequestException not ServiceException!

2025-01-20 07:52 UTC, kimdahee0815 commented on test/unit/modules/newsletter/newsletter.controller.spec.ts
> +
mockResolvedValue should be true rather than nonvalue

2025-01-20 07:52 UTC, kimdahee0815 commented on src/modules/newsletter/newsletter.service.ts
> +
I think this should return true as a result and if there is error throws error.
function name is isCreateNewsLetterSubscriptionDtoValid, so I think returning boolean value suits!

2025-01-20 07:52 UTC, kimdahee0815 commented on test/unit/modules/newsletter/newsletter.service.spec.ts
> +  });
As I mentioned earlier above, this one also could be return true, not return anything

2025-01-20 07:52 UTC, kimdahee0815 commented on test/e2e/newsletter.e2e-spec.ts
>    let app: INestApplication;
should go to e2e test commit!

2025-01-20 07:52 UTC, kimdahee0815 commented on src/modules/mail/mail.service.ts
> +      console.error('Failed to send email:', error);
we shouldn't use console, but we can use ServiceException filter
Use ErrorException and add error message for 'Failed to send email' to errorMessages enum file.

2025-01-20 07:52 UTC, kimdahee0815 commented on test/unit/modules/mail/mail.service.spec.ts
> +
I think we should use mock ServiceException error with error messages here, so that it will be clear to see what error was occured. 
Also errorMessage shouldn't be hard coded, but added in errorMessage enum file.

2025-01-20 07:52 UTC, kimdahee0815 commented on test/unit/modules/mail/mail.service.spec.ts
> +
I think we should use mock ServiceException error with error messages here, so that it will be clear to see what error was occured.
Also errorMessage shouldn't be hard coded, but added in errorMessage enum file.

2025-01-22 19:25 UTC, Harian-Elyoth commented on test/unit/modules/newsletter/newsletter.repository.spec.ts
> +    });
We are in the repository spec. We only test the function getSubsccriptionByEmail and if it does not find something it returns null. The 404 Error may be tested in the e2e test

2025-01-22 19:29 UTC, Harian-Elyoth commented on test/unit/modules/newsletter/newsletter.controller.spec.ts
> +
This return nothing if it's valid or it throws an exception

2025-03-12 11:02 UTC, merged