feat: change database model and add labels
Think-Storm/Backend pull request #80
Opened 2024-11-22 13:02 UTC by Harian-Elyoth

@hcanon42 & @kimdahee0815 
I would like to have your opinion on this, 
I created multiple languages
I created the technical labels (tech stack Javascript) and the domainLabel (Fintech, Health, FoodTech) (maybe we need to change the name)
A project can have technical and domain labels
A user can have skills and interests

And i regrouped the public information such as the bio etc in the user profile

2024-11-23 02:03 UTC, kimdahee0815 requested changes
Everything except for the parts I requested review seems great!
Nice work

2024-11-23 02:03 UTC, kimdahee0815 commented on prisma/schema.prisma
> +  user              User                 @relation(fields: [userId], references: [id])
I think adding 'language' here could be better, since we will be able to know what languages user can use

2024-11-23 02:03 UTC, kimdahee0815 commented on prisma/schema.prisma
if we add language in userProfile, userProfile UserProfile[] should be added here

2024-12-11 10:51 UTC, Harian-Elyoth commented
> Everything except for the parts I requested review seems great! Nice work

@kimdahee0815  You already have done the changes no ?

2024-12-11 11:02 UTC, merged