Feature/update project api 56
Think-Storm/Backend pull request #86
Opened 2024-12-17 09:11 UTC by Harian-Elyoth

2025-01-07 21:31 UTC, Harian-Elyoth commented
@minju25kim @kimdahee0815 Let's review this pull request ;D

2025-01-09 03:13 UTC, kimdahee0815 requested changes
Other parts are great, especially where you arrnaged all the files related to utils files 👍🏻
Check out the reviews I left and let me know if there's any questions!

2025-01-09 03:13 UTC, kimdahee0815 commented on test/e2e/project.e2e-spec.ts
> +    });
Could you also add the test if technical labels and domain labels data are updated to new data?

2025-01-09 03:13 UTC, kimdahee0815 commented on test/e2e/project.e2e-spec.ts
> +
Could you try using this login function instead manually creating token? 

const response = await request(app.getHttpServer())
        .post('/login')
        .send(defaultLoginUserDto)
        .expect(200);

After you login then you will get user data from response like above.

return res.send({
      message: 'login success',
      data: loggedInUser,
    });

This is the form of response.

And then you can get token from 

response.headers.authorization, response.headers['set-cookie'][0])

2025-01-09 03:13 UTC, kimdahee0815 commented on test/e2e/project.e2e-spec.ts
> +        .set('Authorization', `Bearer ${token}`) // Add JWT token to request
Could you change .set('Authorization', token) part to token that you got from login function above?
Also if you set Authorization header here, then is there any logic inside service that checks user's authorization token?
You gotta add part where user's authorization is founder's authorization token and if it isn't it should send error 'ForbiddenException'.

2025-01-09 03:13 UTC, kimdahee0815 commented on test/unit/modules/project/project.service.spec.ts
> +
expectedResponseDto should be defaultProjectUpdateResponseDto, not defaultProjectResponseDto
you should create defaultProjectUpdateResponseDto for checking if project is updated correctly or not
defaultProjectUpdateResponseDto should be the result of the updated project including changed domain labels or techincal labels, basically including the changed data in defaultUpdateProjectDto

export const defaultUpdateProjectDto = {
  id: 1,
  founderId: 1,
  title: 'updatedTitle',
  description: 'updatedDescription',
  status: ProjectStatus.Complete,
  languageCode: LanguageCode.FR,
  goal: Goal.OpenSource,
  milestone: new Date('2021-01-01'),
  domainLabels: ['Science', 'Technology'],
  technicalLabels: ['TypeScript', 'GraphQL'],
};

2025-01-09 03:13 UTC, kimdahee0815 commented on src/modules/project/project.repository.ts
> +    });
This file should go to the 'add update project api' commit!

2025-01-09 03:13 UTC, kimdahee0815 commented on src/modules/project/project.service.ts
> +      );
if 'authorization' is added for checking if the user is forbidden to update or not, you should check 
1) if the user is logged in (by using @UseGuards(JwtAuthGuard) to controller - just like getUserById (commented out part))
2) if the user is logged in, then get jwt token from authorization header or cookie and use verifyAndDecodeToken method in jwt strategy. Get user id from this function.
3) check if user id from process 2 is same as found project's founder Id, if it's same then this user is founder so the user can update. If not, then send FORBIDDEN error.

2025-01-10 12:50 UTC, Harian-Elyoth commented on test/unit/modules/project/project.service.spec.ts
> +
I dont really get it since the dto is the same. it will be the same struct defining the project with the new value no ?

2025-01-10 17:51 UTC, Harian-Elyoth commented on test/e2e/project.e2e-spec.ts
> +
Finally I dont think this is a good idea, Don't you think we should isolate the test ?
Here we want to test the project update API function, we do not want this test to fail because of a modification in the login function. We may want to keep mocking the login interface

2025-01-11 06:55 UTC, kimdahee0815 commented on test/e2e/project.e2e-spec.ts
> +
I think i need more clarification here. What do you mean by isolating the test??

2025-01-11 06:57 UTC, kimdahee0815 commented on test/unit/modules/project/project.service.spec.ts
> +
It's not really the same. defaultUpdateProjectDto is the result you get when you update project.
So, what I mean here is that you should check if updated project result is same as defaultUpdateProjectDto

2025-01-20 02:17 UTC, kimdahee0815 requested changes
e2e tests are perfect! 
Other than small changes I think should be made, all seems great 😎🤙🏻

2025-01-20 02:17 UTC, kimdahee0815 commented on src/modules/project/dtos/updateProjectRequest.dto.ts
> +  @IsString()
Shouldn't it be IsEnum(LanguageCode) here??

2025-01-20 02:17 UTC, kimdahee0815 commented on src/modules/project/project.repository.ts
> +      },
like, involvement, joinRequest should be changed to Like, Involvement, JoinRequest! 
Otherwise, npm run start:dev will give an error.
In index.d.ts, type ProjectInclude or UserInclude has them all capital letters.

2025-01-20 02:17 UTC, kimdahee0815 commented on test/unit/modules/project/project.controller.spec.ts
>  });
There isn't updateProject function unit test for controller!

2025-01-20 02:17 UTC, kimdahee0815 commented on test/unit/modules/project/project.repository.spec.ts
> +  });
I think comparing with just hard coding string like this isn't the best practice.
As I mentioned earlier, best way could be creating defaultProjectUpdateResponseDto in project.utils.ts and compare the result with elements inside of defaultProjectUpdateResponseDto.

2025-01-20 02:17 UTC, kimdahee0815 commented on test/unit/modules/project/project.service.spec.ts
> +
Shouldn't mock the updateProject function here, since this the result we wanna test on. 
from here we just call await updateProject(defaultUpdateDto, defaultUpdateProjectDto.founderId), get the result from this and check if the results are same as the defaultUpdateDto and expectedResponseDto. 
Also, you should also check if technicallabels and domainlabels were updated as well.

2025-01-22 19:45 UTC, Harian-Elyoth commented on test/unit/modules/project/project.controller.spec.ts
>  });
Might need your help to mock a request with the JWT Guards activated

2025-01-22 19:53 UTC, Harian-Elyoth commented on test/unit/modules/project/project.service.spec.ts
> +
I do think that in the service test we only test the functions in the service.
All the functions in the updateProjectFunction should be mocked

2025-01-24 15:19 UTC, Harian-Elyoth commented on src/modules/project/project.repository.ts
> +      },
you may need to migrate, generate, and seed again your database

2025-01-25 08:16 UTC, kimdahee0815 requested changes
Threre are small changes that should be made
I think controller unit test, you did a really good job on that!! 👍🏻
I needed to study that part as well and I learned a lot thanks!

2025-01-25 08:16 UTC, kimdahee0815 commented on src/modules/project/project.repository.ts
> +      },
got it!

2025-01-25 08:16 UTC, kimdahee0815 commented on test/unit/modules/project/project.service.spec.ts
> +
I think I didn't see that you mocked the updateProject function in the repository!
I thought you mocked the updateProject in service, my mistake.
You are right, every functions except for the function we wanna test on should be mocked.
But, that being said, I think there are small changes that should be made.
dbSpy function updateProject mockResolvedValue should be defaultUpdatedProject, since this is the changed updated project result after the update function 
And I think expectedResponseDto should be defaultUpdateProjectResponseDto( it should be created in project.utils)
technical labels and domain labels don't have to be tested on since we get the result from include, so just like you did expectedResponseDto.technicalLabels = undefined;
expectedResponseDto.domainLabels = undefined;
these can be dealt with like above

2025-01-25 08:16 UTC, kimdahee0815 commented on test/unit/modules/project/project.repository.spec.ts
> +      );
domainLables and technicalLabels are not tested on here!

2025-02-01 09:07 UTC, kimdahee0815 requested changes
Other than small changes I think everything looks great! 👍🏻😊

2025-02-01 09:07 UTC, kimdahee0815 commented on test/utils/auth.utils.ts
> +          authorization: `Bearer ${token}`,
could you change this part to createAuthHeader(token) ? 
It will be better to use function than constant string here.

2025-02-01 09:07 UTC, kimdahee0815 commented on test/utils/jwt.utils.ts
> +
About MockJwtService and createMockJwtToken part, we use passport to get token instead of JwtService from nestjs.
I think this can be confusing to put it here since we use different method, so maybe it should be deleted. 
Instead, we can directly mock inside of project controller unit test file.

2025-02-01 09:07 UTC, kimdahee0815 commented on src/modules/project/dtos/project.mapper.ts
> +
We can maybe separate this part to separate file in dtos or different folder named 'types' and can export this type from that file.

2025-02-01 09:07 UTC, kimdahee0815 commented on src/modules/project/dtos/updateProjectRequest.dto.ts
> +  @IsOptional()
isNotEmpty instead of IsOptional.
IsNotEmpty checks if the input is not null, not undefined, not empty string.
Since this is PUT request (not PATCH) and we send all the data from frontend, we wanna make sure that we get data that is valid to be updated in the project DB.

2025-02-01 09:07 UTC, kimdahee0815 commented on src/modules/project/dtos/updateProjectRequest.dto.ts
> +  @IsOptional()
isNotEmpty instead of IsOptional.
Same reason above.

2025-02-01 09:07 UTC, kimdahee0815 commented on src/modules/project/dtos/updateProjectRequest.dto.ts
> +  @IsOptional()
isNotEmpty instead of IsOptional.
Same reason above.

2025-02-01 09:07 UTC, kimdahee0815 commented on src/modules/project/dtos/updateProjectRequest.dto.ts
> +  @IsOptional()
isNotEmpty instead of IsOptional.
Same reason above.

2025-02-01 09:07 UTC, kimdahee0815 commented on src/modules/project/dtos/updateProjectRequest.dto.ts
> +  @IsOptional()
isNotEmpty instead of IsOptional.
Same reason above.

2025-02-01 09:07 UTC, kimdahee0815 commented on src/modules/project/dtos/updateProjectRequest.dto.ts
> +  @IsOptional()
isNotEmpty instead of IsOptional.
Same reason above.
Especially if domainLabels are not sent, it gives an error, so this should be dealt with.
![image](https://github.com/user-attachments/assets/505767b4-1836-4989-8014-62106ed8c117)
this occurs because of the map function inside of service layer. since there is no domainLabels sent, it execute map function to null.

2025-02-01 09:07 UTC, kimdahee0815 commented on src/modules/project/dtos/updateProjectRequest.dto.ts
> +  @IsOptional()
isNotEmpty instead of IsOptional.
Same reason above.
Same case as domainLabels

2025-02-01 09:07 UTC, kimdahee0815 commented on test/unit/modules/project/project.controller.spec.ts
>    });
Since we use JwtGuard from passport, I think using MockJwtService that uses native jwtService from nestjs could be different than the real results, although it works and tests passed as well.
We can maybe comment this part out,
![image](https://github.com/user-attachments/assets/bd0d29d4-71df-4132-9659-1b8652b71b00)
and directly mock like this.
![image](https://github.com/user-attachments/assets/0a875d16-31bd-4015-bac8-bedcfb6bb858)
This way we will be using passport jwt strategy :-)

2025-02-01 09:07 UTC, kimdahee0815 commented on test/unit/modules/project/project.controller.spec.ts
> +      mockRequest.headers = { authorization: `Bearer ${mockJwtToken}` };
mockRequest.headers = createAuthHeader(mockJwtToken) function can be used here instead.

2025-02-01 09:07 UTC, kimdahee0815 commented on test/unit/modules/project/project.repository.spec.ts
> +
this can be separated to different file and exported from that file.

2025-02-03 12:01 UTC, merged